# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1f438cd11f54d8a5ff7f1a5574beb4c313805e961f297f592a72d725441ea68a058dd769898893cb9f85123586732a2250a9abe5f5997972f938413051b894f

test:
  secret_key_base: 91a155b6021626038cbb7a688c6ac286afa292e6c6673afaec16c6c514df5e204c43a50c7d6684b9ba741fdedbd3ca752f9a4bc2acf0d1d21e2dd7fecba50cb4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
